config/routes.rb
# == Route Map
#
#                    Prefix Verb     URI Pattern                            Controller#Action
#               users_index GET      /users/index(.:format)                 users#index
#                users_show GET      /users/show(.:format)                  users#show
#          new_user_session GET      /users/sign_in(.:format)               users/sessions#new
#              user_session POST     /users/sign_in(.:format)               users/sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)              users/sessions#destroy
#   user_omniauth_authorize GET|POST /users/auth/:provider(.:format)        users/omniauth_callbacks#passthru {:provider=>/facebook|twitter/}
#    user_omniauth_callback GET|POST /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:facebook|twitter)
#             user_password POST     /users/password(.:format)              users/passwords#create
#         new_user_password GET      /users/password/new(.:format)          users/passwords#new
#        edit_user_password GET      /users/password/edit(.:format)         users/passwords#edit
#                           PATCH    /users/password(.:format)              users/passwords#update
#                           PUT      /users/password(.:format)              users/passwords#update
#  cancel_user_registration GET      /users/cancel(.:format)                users/registrations#cancel
#         user_registration POST     /users(.:format)                       users/registrations#create
#     new_user_registration GET      /users/sign_up(.:format)               users/registrations#new
#    edit_user_registration GET      /users/edit(.:format)                  users/registrations#edit
#                           PATCH    /users(.:format)                       users/registrations#update
#                           PUT      /users(.:format)                       users/registrations#update
#                           DELETE   /users(.:format)                       users/registrations#destroy
#         user_confirmation POST     /users/confirmation(.:format)          devise/confirmations#create
#     new_user_confirmation GET      /users/confirmation/new(.:format)      devise/confirmations#new
#                           GET      /users/confirmation(.:format)          devise/confirmations#show
#                     blogs GET      /blogs(.:format)                       blogs#index
#                           POST     /blogs(.:format)                       blogs#create
#                  new_blog GET      /blogs/new(.:format)                   blogs#new
#                 edit_blog GET      /blogs/:id/edit(.:format)              blogs#edit
#                      blog GET      /blogs/:id(.:format)                   blogs#show
#                           PATCH    /blogs/:id(.:format)                   blogs#update
#                           PUT      /blogs/:id(.:format)                   blogs#update
#                           DELETE   /blogs/:id(.:format)                   blogs#destroy
#                           GET      /blogs(.:format)                       blogs#index
#                      root GET      /                                      top#index
#                       top GET      /top(.:format)                         top#index
#                     entry GET      /entry(.:format)                       entries#new
#                           POST     /entry(.:format)                       entries#new
#                   confirm POST     /confirm(.:format)                     entries#confirm
#                    thanks POST     /thanks(.:format)                      entries#thanks
# rambulance_exceptions_app          /rambulance                            Rambulance::ExceptionsApp
#

Rails.application.routes.draw do
  
  get 'relationship/create'

  get 'relationship/destroy'

  resources :answers
  resources :qs do
        resources :answers
  end
  resources :comments
  get 'users/index'

  get 'users/show'

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks" 
  }
     #root to:"top#index"
     resources :blogs do
        resources :comments
     end
     get 'blogs', to: 'blogs#index'
     root to: 'top#index'
     get 'top' => 'top#index'
     get 'entry' => 'entries#new'
     post 'entry' => 'entries#new'
     post 'confirm' => 'entries#confirm'
     post 'thanks' => 'entries#thanks'
     get 'detail' => 'entries#detail'
     #get 'login' => 'entries#login'
     
     resources :users, only:[:show,:edit,:update,:index] do
      member do
        get :following, :followers
      end
     end
     resources :relationship, only:[:create,:destroy] 
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  contact    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Entry < ActiveRecord::Base
    validates :name, presence: true
     #validates :email, presence: true
    #validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, format: {with: VALID_EMAIL_REGEX}, unless: "email.empty?"
    validates :email, presence: true
    validates :contact,presence: true
    validates :title,presence: true
    # require 'mail'

    # Mail.defaults do
    #   delivery_method :smtp, {
    #     :address => "smtp.gmail.com",
    #     :port => 587,
    #     :domain => 'example.com',
    #     :user_name => 'hmwehmwe.91@gmail.com',
    #     :password => 'handsforeverforevertogether',
    #     :authentication => 'plain',
    #     :enable_starttls_auto => true
    #   }
    # end
    
    # m = Mail.new do
    #   from 'hmwehmwe.91@gmail.com' #"<送信元メールアドレス>"
    #   to   'infant1500@gmail.com'#"<送信先メールアドレス>"
    #   subject "test mail subject"
    #   body "テストメールです"
    # end
    
    # # 本文のエンコーディング設定。これを書かないと実行時にワーニングが出る
    # m.charset = "UTF-8"
    # m.content_transfer_encoding = "8bit"
    # m.deliver
end

app/controllers/entries_controller.rb
# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  contact    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EntriesController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    #before_action :logged_in_user, only: [:edit, :update]
    #before_action :correct_user,   only: [:edit, :update]
    before_filter :authenticate_user!
    def new 
        @entry =  Entry.new
        if params[:back]
        @entry = Entry.new(confirm_params)
        end
    end
    def confirm
        @entry = Entry.new(confirm_params)
        if @entry.valid? # if true
            render action: 'confirm'
       elsif params[:back] # back page data remain
        render action: 'new'
        else 
           @entry.save
            render action: 'new'
        end
    end
    def thanks
        @entry = Entry.new(confirm_params)
        
         #render :text => 'send finish'
        @entry.save
        NoticeMailer.sendmail_confirm(@entry).deliver
        # if @entry.deliver
        #   flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
        # else
        #   flash.now[:error] = 'Cannot send message.'
        #   render :new
        # end
       # end
    end
    def detail
        @entry = Entry.all
       #NoticeMailer.receive(@entry)
    end
    private  #protect hacking
    def confirm_params
       params.require(:entry).permit(:name, :email, :contact, :title) 
      
    end
   # def logged_in_user
      #unless logged_in?
       # store_location
        #flash[:danger] = "ログインしてください。."
        #redirect_to login_url
     # end
    #end
    #def correct_user
      #@user = User.find(params[:id])
      ##redirect_to(root_url) unless @user == current_user
      #redirect_to(root_url) unless current_user?(@user)
    #end
end

app/helpers/entries_helper.rb
# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  contact    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module EntriesHelper
end

app/views/entries/confirm.html.erb
<style>
    .width {
        width: 150px;
    }
    table tr td {
        padding-top: 10px;
    }
</style>
<div class="container">
    <table>
    <%= form_for @entry, url: thanks_path do |f| %>
    <tr>
     <td class="width">件名「タイトル』</td>
     <td><%= f.text_field :title %></td>
     
     </tr>
    <tr>
     <td class="width">名前</td>
     <td><%= f.text_field :name %></td>
     </tr>
     <tr>
         <td class="width">メールアドレス</td>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
          <td class="width">お問い合わせ内容</td>
       <td><%= f.text_area :contact %></td>
       </tr>
   </table>
  <p class="align"><%= f.submit '保存', :class => 'button' %></p>
<% end %>
<%= form_for @entry, url: entry_path do |f| %>
     <p class="align"><%= f.submit '戻る',:name =>'back', :class => 'button' %></p>
     <%= f.hidden_field :name %>
     <%= f.hidden_field :email %>
     <%= f.hidden_field :contact %>
    
<% end %>
</div>

app/views/entries/detail.html.erb
<style>
    table tr td {
        min-width:150px; 
    }
    table tr td{
        text-align:center;
    }
</style>

<div class="container">
    <h3 style="color:#9966ff">お問い合わせ一覧</h3>
    <hr class="colorgraph">
    <% @entry.each do |i| %>
        <table>
            <tr>
                <td><span style="color:#9966ff">件名:</span></td>
                <td><%= i.title %><br/></td>
            </tr>
            <tr>
                <td><span style="color:#9966ff">名前:</span></td>
                <td><%= i.name %><br/></td>
            </tr>
            <tr> 
                <td><span style="color:#9966ff">お問い合わせ内容:</span></td>
                <td><p><%= simple_format(i.contact) %></td>
            </tr> 
            <tr>
                <td><span style="color:#9966ff">日時:</span></td>
                <td><%= i.created_at %></td>
            </tr>
            <tr>
                <td><span style="color:#9966ff">メール:</span></td>
                <td><%= i.email %></td>
            </tr>
        
         </table>
         <hr style="width:100%;background-color:#009933;height:1px;">
        
         
         
    <% end %>
            
           
        
        
        
    
    
    

</div>

app/views/entries/login.html.erb
<body class="body_index">
    
</body>

app/views/entries/new.html.erb
<style>
    .width {
        width: 150px;
    }
    table tr td {
        padding-top:10px;
    }
</style>
<div class="container">
    <% if @entry.errors.any? %>
    <div class="need"  style="list-style:none;">
       <ul> <% @entry.errors.full_messages.each do |message| %>
     <li style="list-style:none;"> <h3><%= message %></h3></li>
      </ul>
        <% end %> 
    </div>
    <% end %>
    <%= form_for @entry, url: confirm_path do |f| %>
<table>
    <tr>
        <td class="width">件名『タイトル』<span class="need">(*)</span></td>
        <td><%= f.text_field :title %></td>
    </tr>
    <tr>
         <td class="width">名前<span class="need">(*)</span></td>
         <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <td class="width">メールアドレス<span class="need">(*)</span></td>
         <td><%= f.text_field :email %></td>
    </tr>
    <tr>
        <td class="width">お問い合わせ内容</td>
        <td><%= f.text_area :contact %></td> 
    </tr>
</table>
<p class="align"><%= f.submit '確認', :class => 'button' %></p>
 <% end %>
</div>

app/views/entries/thanks.html.erb
<div class="container">
<h4>お問い合わせ完了メーイルを送ります。チェックしてください。</h4>
<h3>完了です。ありがとうございました。</h3>

<p class="button"><%= link_to 'トップページ', top_path %></p>
</div>