config/routes.rb
# == Route Map
#
#                    Prefix Verb     URI Pattern                            Controller#Action
#               users_index GET      /users/index(.:format)                 users#index
#                users_show GET      /users/show(.:format)                  users#show
#          new_user_session GET      /users/sign_in(.:format)               users/sessions#new
#              user_session POST     /users/sign_in(.:format)               users/sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)              users/sessions#destroy
#   user_omniauth_authorize GET|POST /users/auth/:provider(.:format)        users/omniauth_callbacks#passthru {:provider=>/facebook|twitter/}
#    user_omniauth_callback GET|POST /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:facebook|twitter)
#             user_password POST     /users/password(.:format)              users/passwords#create
#         new_user_password GET      /users/password/new(.:format)          users/passwords#new
#        edit_user_password GET      /users/password/edit(.:format)         users/passwords#edit
#                           PATCH    /users/password(.:format)              users/passwords#update
#                           PUT      /users/password(.:format)              users/passwords#update
#  cancel_user_registration GET      /users/cancel(.:format)                users/registrations#cancel
#         user_registration POST     /users(.:format)                       users/registrations#create
#     new_user_registration GET      /users/sign_up(.:format)               users/registrations#new
#    edit_user_registration GET      /users/edit(.:format)                  users/registrations#edit
#                           PATCH    /users(.:format)                       users/registrations#update
#                           PUT      /users(.:format)                       users/registrations#update
#                           DELETE   /users(.:format)                       users/registrations#destroy
#         user_confirmation POST     /users/confirmation(.:format)          devise/confirmations#create
#     new_user_confirmation GET      /users/confirmation/new(.:format)      devise/confirmations#new
#                           GET      /users/confirmation(.:format)          devise/confirmations#show
#                     blogs GET      /blogs(.:format)                       blogs#index
#                           POST     /blogs(.:format)                       blogs#create
#                  new_blog GET      /blogs/new(.:format)                   blogs#new
#                 edit_blog GET      /blogs/:id/edit(.:format)              blogs#edit
#                      blog GET      /blogs/:id(.:format)                   blogs#show
#                           PATCH    /blogs/:id(.:format)                   blogs#update
#                           PUT      /blogs/:id(.:format)                   blogs#update
#                           DELETE   /blogs/:id(.:format)                   blogs#destroy
#                           GET      /blogs(.:format)                       blogs#index
#                      root GET      /                                      top#index
#                       top GET      /top(.:format)                         top#index
#                     entry GET      /entry(.:format)                       entries#new
#                           POST     /entry(.:format)                       entries#new
#                   confirm POST     /confirm(.:format)                     entries#confirm
#                    thanks POST     /thanks(.:format)                      entries#thanks
# rambulance_exceptions_app          /rambulance                            Rambulance::ExceptionsApp
#

Rails.application.routes.draw do
  
  get 'relationship/create'

  get 'relationship/destroy'

  resources :answers
  resources :qs do
        resources :answers
  end
  resources :comments
  get 'users/index'

  get 'users/show'

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks" 
  }
     #root to:"top#index"
     resources :blogs do
        resources :comments
     end
     get 'blogs', to: 'blogs#index'
     root to: 'top#index'
     get 'top' => 'top#index'
     get 'entry' => 'entries#new'
     post 'entry' => 'entries#new'
     post 'confirm' => 'entries#confirm'
     post 'thanks' => 'entries#thanks'
     get 'detail' => 'entries#detail'
     #get 'login' => 'entries#login'
     
     resources :users, only:[:show,:edit,:update,:index] do
      member do
        get :following, :followers
      end
     end
     resources :relationship, only:[:create,:destroy] 
end

app/models/q.rb
class Q < ActiveRecord::Base
    belongs_to :user
    has_many :answers, dependent: :destroy
    validates :title,presence: true
    validates :content,presence: true
    validates :category,presence: true
    validates :language,presence: true
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
  before_action :set_q, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /qs
  # GET /qs.json
  def index
    @qs = Q.all
  end

  # GET /qs/1
  # GET /qs/1.json
  def show
    #@q_form = @q.answers.build
    @answer = @q.answers.build
    @answers = @q.answers
  end

  # GET /qs/new
  def new
    @q = Q.new
  end

  # GET /qs/1/edit
  def edit
  end

  # POST /qs
  # POST /qs.json
  def create
    #@q = Q.new(q_params)
    @q = current_user.qs.build(q_params)

    respond_to do |format|
      if @q.save
        
        format.html { redirect_to @q, notice: '質疑の作成に成功しました。' }
        format.json { render :show, status: :created, location: @q }
        QAmailer.sendmail_confirm(@q).deliver
      else
        format.html { render :new }
        format.json { render json: @q.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qs/1
  # PATCH/PUT /qs/1.json
  def update
    respond_to do |format|
      if @q.update(q_params)
        format.html { redirect_to @q, notice: '質疑の更新に成功しました。' }
        format.json { render :show, status: :ok, location: @q }
      else
        format.html { render :edit }
        format.json { render json: @q.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qs/1
  # DELETE /qs/1.json
  def destroy
    @q.destroy
    respond_to do |format|
      format.html { redirect_to qs_url, notice: '質疑を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_q
      @q = Q.find(params[:id])
    end
    
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def q_params
      #params.fetch(:q, {})
      params.require(:q).permit(:title,:content,:user_id,:category,:language)
    end
end

app/helpers/qs_helper.rb
module QsHelper
end

app/views/qs/_form.html.erb
<%= form_for(@q) do |f| %>
  <% if @q.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@q.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @q.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
  
  <form role="form">
    <div class="form-group">
      <label>タイトル:</label>
      <%= f.text_field :title, :autofocus => true, :class => 'form-control input-lg'  %>
    </div>
    <div class="form-group">
      <label for="sel1">カテゴリ:</label>
      <%= f.select :category, [["選択してください。", ""], "Postgresql", "SQLite", "MySQL", "その他"], :class => 'form-control input-lg' %>
    </div>
    <div class="form-group">
      <label>言語:</label>
      <%= f.select :language, [["選択してください。", ""], "Ruby on Rails", "JavaScript", "Bootstrap", "その他"], :class => 'form-control input-lg' %>
      </select>
    </div>
    <div class="form-group">
      <label>質問内容:</label>
      <%= f.text_area :content, :autofocus => true, :class => 'form-control input-lg'  %>
    </div>
      <%= f.submit '登録', :class => 'btn btn-primary' %>
      <%= link_to 'Back', qs_path, class:"btn btn-success" %>
  </form>
  </div>
  
<% end %>

app/views/qs/edit.html.erb
<div class="container">
  <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
             質問の詳細
          </h4>
        </div>
      </div>
      <%= render 'form' %>
      
  </div>
</div>

app/views/qs/index.html.erb
<div class="container">
  <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
             質問一覧
          </h4>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="col-xs-4">投稿者名</th><th class="col-xs-6">タイトル</th>
            </tr>
          </thead>
          <tbody>
            <% @qs.each do |q| %>
              <tr>
                <td><%= q.user.name %></td>
                <td><%= link_to q.title, q %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
  <%= link_to '新質問をする', new_q_path, class:"btn btn-info" %>
</div>

app/views/qs/new.html.erb
<div class="container">
  <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
             質問する
          </h4>
        </div>
        
      </div>
      
      
      
<%= render 'form' %>

app/views/qs/show.html.erb
<div class="container">
  <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
             質問の詳細
          </h4>
        </div>
        <table class="table table-striped">
            <tr>
                <th class="col-xs-4">投稿者名:</th>
                 <td class="col-xs-5"><%= @q.user.name %></td>
            </tr>
            <tr>
                <th class="col-xs-4">タイトル:</th>
                <td class="col-xs-5"><%= @q.title %></td>
            </tr>
            <tr>
                <th class="col-xs-4">カテゴリ:</th>
                <td class="col-xs-5"><%= @q.category %></td>
            </tr>
            <tr>
                <th class="col-xs-4">言語:</th>
                <td class="col-xs-5"><%= @q.language %></td>
            </tr>
            <tr>
                <th class="col-xs-4">質問内容:</th>
                <td class="col-xs-5"><%= simple_format(@q.content) %></td>
            </tr>
        </table>
       
      </div>
       
  </div>
  <div class="row">
      <% if current_user.id==@q.user_id %>
        <span><%= link_to '編集', edit_q_path(@q), class:"btn btn-warning" %></span>
        <span><%= link_to '削除', @q, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></span>
      <% end %>
        <span><%= link_to '戻る', qs_path, class:"btn btn-success" %></span>
  </div>
  <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
             質問のコメント
          </h4>
        </div>
        
            <div id="comments_area">
                  <%= render partial: 'answers/index', locals: {answers: @q.answers} %>
            </div>
                <%= render partial: 'answers/form', locals: {answers: @q.answers} %>
       
      </div>
       
  </div>
  
</div>