config/routes.rb
# == Route Map
#
#                    Prefix Verb     URI Pattern                            Controller#Action
#               users_index GET      /users/index(.:format)                 users#index
#                users_show GET      /users/show(.:format)                  users#show
#          new_user_session GET      /users/sign_in(.:format)               users/sessions#new
#              user_session POST     /users/sign_in(.:format)               users/sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)              users/sessions#destroy
#   user_omniauth_authorize GET|POST /users/auth/:provider(.:format)        users/omniauth_callbacks#passthru {:provider=>/facebook|twitter/}
#    user_omniauth_callback GET|POST /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:facebook|twitter)
#             user_password POST     /users/password(.:format)              users/passwords#create
#         new_user_password GET      /users/password/new(.:format)          users/passwords#new
#        edit_user_password GET      /users/password/edit(.:format)         users/passwords#edit
#                           PATCH    /users/password(.:format)              users/passwords#update
#                           PUT      /users/password(.:format)              users/passwords#update
#  cancel_user_registration GET      /users/cancel(.:format)                users/registrations#cancel
#         user_registration POST     /users(.:format)                       users/registrations#create
#     new_user_registration GET      /users/sign_up(.:format)               users/registrations#new
#    edit_user_registration GET      /users/edit(.:format)                  users/registrations#edit
#                           PATCH    /users(.:format)                       users/registrations#update
#                           PUT      /users(.:format)                       users/registrations#update
#                           DELETE   /users(.:format)                       users/registrations#destroy
#         user_confirmation POST     /users/confirmation(.:format)          devise/confirmations#create
#     new_user_confirmation GET      /users/confirmation/new(.:format)      devise/confirmations#new
#                           GET      /users/confirmation(.:format)          devise/confirmations#show
#                     blogs GET      /blogs(.:format)                       blogs#index
#                           POST     /blogs(.:format)                       blogs#create
#                  new_blog GET      /blogs/new(.:format)                   blogs#new
#                 edit_blog GET      /blogs/:id/edit(.:format)              blogs#edit
#                      blog GET      /blogs/:id(.:format)                   blogs#show
#                           PATCH    /blogs/:id(.:format)                   blogs#update
#                           PUT      /blogs/:id(.:format)                   blogs#update
#                           DELETE   /blogs/:id(.:format)                   blogs#destroy
#                           GET      /blogs(.:format)                       blogs#index
#                      root GET      /                                      top#index
#                       top GET      /top(.:format)                         top#index
#                     entry GET      /entry(.:format)                       entries#new
#                           POST     /entry(.:format)                       entries#new
#                   confirm POST     /confirm(.:format)                     entries#confirm
#                    thanks POST     /thanks(.:format)                      entries#thanks
# rambulance_exceptions_app          /rambulance                            Rambulance::ExceptionsApp
#

Rails.application.routes.draw do
  
  get 'relationship/create'

  get 'relationship/destroy'

  resources :answers
  resources :qs do
        resources :answers
  end
  resources :comments
  get 'users/index'

  get 'users/show'

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks" 
  }
     #root to:"top#index"
     resources :blogs do
        resources :comments
     end
     get 'blogs', to: 'blogs#index'
     root to: 'top#index'
     get 'top' => 'top#index'
     get 'entry' => 'entries#new'
     post 'entry' => 'entries#new'
     post 'confirm' => 'entries#confirm'
     post 'thanks' => 'entries#thanks'
     get 'detail' => 'entries#detail'
     #get 'login' => 'entries#login'
     
     resources :users, only:[:show,:edit,:update,:index] do
      member do
        get :following, :followers
      end
     end
     resources :relationship, only:[:create,:destroy] 
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :q
  belongs_to :user
  validates :content,presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer =current_user.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to q_path(@answer.q), notice: 'コメントの作成に成功しました。' }
        format.json { render :show, status: :created, location: @answer }
        @q = @answer.q
        @answers = @q.answers
        format.js {render :index, notice: 'コメントの作成に成功しました。'}
        Answermailer.sendmail_confirm(@answer).deliver
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to q_path(@answer.q), notice: 'コメントは正常に更新されました。' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to q_path(@answer.q), notice: 'コメントが正常に消されました。' }
      format.json { head :no_content }
      @q = @answer.q
      format.js { render :index, notice: 'コメントが正常に消されました。' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:q_id, :user_id, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<div class="container">
<%= form_for(@answer,remote: true) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :q_id %>
  <%= f.hidden_field :user_id %>
  <div class="field">
    <%= f.label :コメント %><br>
    <%= f.text_area :content, :id => 'message' %>
  </div> 
    <br/><%= f.submit class: 'btn btn-info' %>
<% end %>
</div>

app/views/answers/_index.html.erb
        <table class="table table-striped">
            <thead>
              <tr>
                <th>投稿者名</th><th>コメント内容</th><th></th>
              </tr>
            </thead>
            <% answers.each do |answer| %>
            <% unless answer.id.nil? %>
            <tbody>
              <tr>
                <td><%= answer.user.name %></td><td><%= simple_format(answer.content) %></td>
                <% if current_user.id== answer.user_id %>
                <td><%= link_to '編集', edit_q_answer_path(@q,answer), class:"btn btn-warning" %>
                    <%= link_to '削除', answer, method: :delete, data: { confirm: '本当に?' }, class:"btn btn-danger" %>
                </td>
                <% end %>
                <% unless current_user.id== answer.user_id %>
                <td><span class="glyphicon glyphicon-refresh"></span></td>
                <% end %>
              </tr>
            </tbody>
            <% end %>
            <% end %>
        </table>
      
    

app/views/answers/edit.html.erb
<div class="container">
  <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
             コメント編集
          </h4>
        </div>
        <%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :q_id %>
  <%= f.hidden_field :user_id %>
  <div class="field">
    <%= f.label :コメント %><br>
    <%= f.text_field :content %>
  </div> 
    <br/><%= f.submit class: 'btn btn-info' %>
    <% end %>
    　</div>
  </div>
  <div class="row">
      <%= link_to 'Back', q_path(@answer.q), class:"btn btn-success" %>
  </div>
</div>

app/views/answers/index.js.erb
$("#comments_area").html("<%=escape_javascript(render partial: 'answers/index',locals: { answers: @q.answers }) %>");
$(':text').val('')
$('#message').val('');

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q:</strong>
  <%= @answer.q %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<p>
  <strong>:</strong>
  <%= @answer.content %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>