config/routes.rb
# == Route Map
#
#                    Prefix Verb     URI Pattern                            Controller#Action
#               users_index GET      /users/index(.:format)                 users#index
#                users_show GET      /users/show(.:format)                  users#show
#          new_user_session GET      /users/sign_in(.:format)               users/sessions#new
#              user_session POST     /users/sign_in(.:format)               users/sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)              users/sessions#destroy
#   user_omniauth_authorize GET|POST /users/auth/:provider(.:format)        users/omniauth_callbacks#passthru {:provider=>/facebook|twitter/}
#    user_omniauth_callback GET|POST /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:facebook|twitter)
#             user_password POST     /users/password(.:format)              users/passwords#create
#         new_user_password GET      /users/password/new(.:format)          users/passwords#new
#        edit_user_password GET      /users/password/edit(.:format)         users/passwords#edit
#                           PATCH    /users/password(.:format)              users/passwords#update
#                           PUT      /users/password(.:format)              users/passwords#update
#  cancel_user_registration GET      /users/cancel(.:format)                users/registrations#cancel
#         user_registration POST     /users(.:format)                       users/registrations#create
#     new_user_registration GET      /users/sign_up(.:format)               users/registrations#new
#    edit_user_registration GET      /users/edit(.:format)                  users/registrations#edit
#                           PATCH    /users(.:format)                       users/registrations#update
#                           PUT      /users(.:format)                       users/registrations#update
#                           DELETE   /users(.:format)                       users/registrations#destroy
#         user_confirmation POST     /users/confirmation(.:format)          devise/confirmations#create
#     new_user_confirmation GET      /users/confirmation/new(.:format)      devise/confirmations#new
#                           GET      /users/confirmation(.:format)          devise/confirmations#show
#                     blogs GET      /blogs(.:format)                       blogs#index
#                           POST     /blogs(.:format)                       blogs#create
#                  new_blog GET      /blogs/new(.:format)                   blogs#new
#                 edit_blog GET      /blogs/:id/edit(.:format)              blogs#edit
#                      blog GET      /blogs/:id(.:format)                   blogs#show
#                           PATCH    /blogs/:id(.:format)                   blogs#update
#                           PUT      /blogs/:id(.:format)                   blogs#update
#                           DELETE   /blogs/:id(.:format)                   blogs#destroy
#                           GET      /blogs(.:format)                       blogs#index
#                      root GET      /                                      top#index
#                       top GET      /top(.:format)                         top#index
#                     entry GET      /entry(.:format)                       entries#new
#                           POST     /entry(.:format)                       entries#new
#                   confirm POST     /confirm(.:format)                     entries#confirm
#                    thanks POST     /thanks(.:format)                      entries#thanks
# rambulance_exceptions_app          /rambulance                            Rambulance::ExceptionsApp
#

Rails.application.routes.draw do
  
  get 'relationship/create'

  get 'relationship/destroy'

  resources :answers
  resources :qs do
        resources :answers
  end
  resources :comments
  get 'users/index'

  get 'users/show'

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks" 
  }
     #root to:"top#index"
     resources :blogs do
        resources :comments
     end
     get 'blogs', to: 'blogs#index'
     root to: 'top#index'
     get 'top' => 'top#index'
     get 'entry' => 'entries#new'
     post 'entry' => 'entries#new'
     post 'confirm' => 'entries#confirm'
     post 'thanks' => 'entries#thanks'
     get 'detail' => 'entries#detail'
     #get 'login' => 'entries#login'
     
     resources :users, only:[:show,:edit,:update,:index] do
      member do
        get :following, :followers
      end
     end
     resources :relationship, only:[:create,:destroy] 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
              </button>
              <a class="navbar-brand">トップページ</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
                <% unless user_signed_in? %>
                <li><%= link_to 'ログイン' ,new_user_session_path, class: "glyphicon glyphicon-log-in button color" %></li>
                <li><%= link_to "facebook認証", user_omniauth_authorize_path(:facebook), class: 'fa fa-facebook-square navbar-link color' %></li> 
                <li><%= link_to "twitter認証", user_omniauth_authorize_path(:twitter), class: 'fa fa-twitter-square navbar-link color' %></li>
                <% end %>
                
                <% if user_signed_in? %>
                  <li class="dropdown"><a class="dropdown-toggle color" data-toggle="dropdown">User<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'マイページ','/users/edit', class: "color" %></li>
                    <li><%= link_to "ユーザ一覧", '/users/index' , class: "color" %> </li>
                  </ul>
                </li> 
                <li class="dropdown"><a class="dropdown-toggle color" data-toggle="dropdown">お問い合わせ<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'お問い合わせ',entry_path, class: "color" %></li>
                    <li><%= link_to "お問い合わせ受信トレイ",  detail_path, class: "color" %></li>
                  </ul>
                </li>  
                <li><%= link_to 'Blog',blogs_path, class: "color" %></li>
                <li><%= link_to 'School_Q&A',qs_path, class: "color" %></li>
                <li><%= link_to 'ログアウト' , destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-user button color" %></li>
                
              </ul>
              
               
                     
                     
                     
                     
                     
                <% end %>
              

            </div>
          </div>
        </nav>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
              </button>
              <a class="navbar-brand">トップページ</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
                <li class=""><%= link_to 'マイページ','/users/edit', class: "color" %></li>
                
                <li><%= link_to 'お問い合わせ','entry', class: "color" %></li>
                <li><%= link_to 'Blog',blogs_path, class: "color" %></li>
                <li><%= link_to "facebook認証", user_omniauth_authorize_path(:facebook), class: 'fa fa-facebook-square navbar-link color' %></li> 
                <li><%= link_to "twitter認証", user_omniauth_authorize_path(:twitter), class: 'fa fa-twitter-square navbar-link color' %></li>
                <li><%= link_to "ユーザー一覧", '/users/index' , class: "color" %> </li>
                <li><%= link_to "お問い合わせ受信トレイ", detail_path, class: "color" %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
               <li><% if user_signed_in? %>
                     <%= link_to 'ログアウト' , destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-user button color" %>
                     <% else %>
                     <%= link_to 'ログイン' ,new_user_session_path, class: "glyphicon glyphicon-log-in button color" %></li> 
                <% end %></ul>
              

            </div>
          </div>
        </nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>